# Enfermedad del corazon

In [150]:
import pandas as pd
df2 = pd.read_csv("heart.csv")
df2.head()
#edad, sexo, colorPecho, trestbps: presionArterial, 
#chol: colesterolSerica, fbs: glucemiaenAyunas, restecg: electrocardiográficosReposo
#thalach: frecuencia cardíaca máxima alcanzada, exang: angina inducida por ejercicio, 
#oldpeak: Depresión del ST inducida por el ejercicio en relación con el reposo
#slope: la pendiente del segmento ST de ejercicio pico, 
#ca: número de vasos principales (0-3) coloreados por la floración
#thal: 3 = normal; 6 = defecto fijo; 7 = defecto reversible

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [126]:
# media
from statistics import mode,stdev
print("media:",sum(df2["age"])/len(df2["age"]))
print("media:",sum(df2["sex"])/len(df2["sex"]))
print("media:",sum(df2["cp"])/len(df2["cp"]))
print("media:",sum(df2["trestbps"])/len(df2["trestbps"]))
print("media:",sum(df2["chol"])/len(df2["chol"]))
print("media:",sum(df2["fbs"])/len(df2["fbs"]))
print("media:",sum(df2["restecg"])/len(df2["restecg"]))
print("media:",sum(df2["thalach"])/len(df2["thalach"]))
print("media:",sum(df2["exang"])/len(df2["exang"]))
print("media:",sum(df2["oldpeak"])/len(df2["oldpeak"]))
print("media:",sum(df2["slope"])/len(df2["slope"]))
print("media:",sum(df2["ca"])/len(df2["ca"]))
print("media:",sum(df2["thal"])/len(df2["thal"]))
print("media:",sum(df2["target"])/len(df2["target"]))
# Moda
print("MODA: ",mode(df2["age"])) 
print("MODA: ",mode(df2["sex"])) 
print("MODA: ",mode(df2["cp"])) 
print("MODA: ",mode(df2["trestbps"])) 
print("MODA: ",mode(df2["fbs"])) 
print("MODA: ",mode(df2["restecg"])) 
print("MODA: ",mode(df2["thalach"])) 
print("MODA: ",mode(df2["exang"])) 
print("MODA: ",mode(df2["oldpeak"])) 
print("MODA: ",mode(df2["slope"])) 
print("MODA: ",mode(df2["ca"])) 
print("MODA: ",mode(df2["thal"])) 
print("MODA: ",mode(df2["target"]))

print("DESV ESTAN: ",stdev(df2["age"]))
print("DESV ESTAN: ",stdev(df2["sex"]))
print("DESV ESTAN: ",stdev(df2["cp"]))
print("DESV ESTAN: ",stdev(df2["trestbps"]))
print("DESV ESTAN: ",stdev(df2["restecg"]))
print("DESV ESTAN: ",stdev(df2["thalach"]))
print("DESV ESTAN: ",stdev(df2["exang"]))
print("DESV ESTAN: ",stdev(df2["oldpeak"]))
print("DESV ESTAN: ",stdev(df2["slope"]))
print("DESV ESTAN: ",stdev(df2["ca"]))
print("DESV ESTAN: ",stdev(df2["thal"]))
print("DESV ESTAN: ",stdev(df2["target"]))

media: 54.366336633663366
media: 0.6831683168316832
media: 0.966996699669967
media: 131.62376237623764
media: 246.26402640264027
media: 0.1485148514851485
media: 0.528052805280528
media: 149.64686468646866
media: 0.32673267326732675
media: 1.0396039603960396
media: 1.3993399339933994
media: 0.7293729372937293
media: 2.3135313531353137
media: 0.5445544554455446
MODA:  58
MODA:  1
MODA:  0
MODA:  120
MODA:  0
MODA:  1
MODA:  162
MODA:  0
MODA:  0.0
MODA:  2
MODA:  0
MODA:  2
MODA:  1
DESV ESTAN:  9.082100989837858
DESV ESTAN:  0.46601082333962385
DESV ESTAN:  1.0320524894832988
DESV ESTAN:  17.538142813517098
DESV ESTAN:  0.5258595963592981
DESV ESTAN:  22.905161114914094
DESV ESTAN:  0.4697944645223165
DESV ESTAN:  1.1610750220686348
DESV ESTAN:  0.616226145345962
DESV ESTAN:  1.022606364969327
DESV ESTAN:  0.6122765072781409
DESV ESTAN:  0.49883478416439136

In [147]:
#Media, moda, desvacionstardar con libreria numpy
import numpy
print("MEDIA:", numpy.mean(df2,axis=0))
print("MODA:", mode(df2["age"]))
print("DESV. STAND:",numpy.std(df2,axis=0))

MEDIA: age          54.366337
sex           0.683168
cp            0.966997
trestbps    131.623762
chol        246.264026
fbs           0.148515
restecg       0.528053
thalach     149.646865
exang         0.326733
oldpeak       1.039604
slope         1.399340
ca            0.729373
thal          2.313531
target        0.544554
dtype: float64
MODA: 58
DESV. STAND: age          9.067102
sex          0.465241
cp           1.030348
trestbps    17.509178
chol        51.745151
fbs          0.355610
restecg      0.524991
thalach     22.867333
exang        0.469019
oldpeak      1.159157
slope        0.615208
ca           1.020918
thal         0.611265
target       0.498011
dtype: float64